"""initial_schema

Revision ID: 7049c4c39a8d
Revises: 
Create Date: 2026-02-28 17:16:45.335581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7049c4c39a8d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('idle_episodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('idle_started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('idle_ended_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('idle_minutes', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_idle_episodes_id'), 'idle_episodes', ['id'], unique=False)
    op.create_index(op.f('ix_idle_episodes_idle_ended_at'), 'idle_episodes', ['idle_ended_at'], unique=False)
    op.create_index(op.f('ix_idle_episodes_idle_started_at'), 'idle_episodes', ['idle_started_at'], unique=False)
    op.create_index(op.f('ix_idle_episodes_user_id'), 'idle_episodes', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=128), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_public_id'), 'users', ['public_id'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('work_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('session_started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('session_ended_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tracked_minutes', sa.Float(), nullable=False),
    sa.Column('active_minutes', sa.Float(), nullable=False),
    sa.Column('deep_work_minutes', sa.Float(), nullable=False),
    sa.Column('engagement_score', sa.Float(), nullable=True),
    sa.Column('context_switch_count', sa.Integer(), nullable=False),
    sa.Column('assigned_tasks', sa.Integer(), nullable=False),
    sa.Column('completed_tasks', sa.Integer(), nullable=False),
    sa.Column('break_minutes', sa.Float(), nullable=False),
    sa.Column('late_night_minutes', sa.Float(), nullable=False),
    sa.Column('weekend_minutes', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_logs_id'), 'work_logs', ['id'], unique=False)
    op.create_index(op.f('ix_work_logs_session_ended_at'), 'work_logs', ['session_ended_at'], unique=False)
    op.create_index(op.f('ix_work_logs_session_started_at'), 'work_logs', ['session_started_at'], unique=False)
    op.create_index(op.f('ix_work_logs_user_id'), 'work_logs', ['user_id'], unique=False)
    op.create_table('work_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'PAUSED', 'COMPLETED', name='sessionstatus'), nullable=False),
    sa.Column('project_name', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_sessions_end_time'), 'work_sessions', ['end_time'], unique=False)
    op.create_index(op.f('ix_work_sessions_id'), 'work_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_work_sessions_start_time'), 'work_sessions', ['start_time'], unique=False)
    op.create_index(op.f('ix_work_sessions_user_id'), 'work_sessions', ['user_id'], unique=False)
    op.create_table('heartbeats',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_idle', sa.Boolean(), nullable=False),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['work_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_heartbeats_id'), 'heartbeats', ['id'], unique=False)
    op.create_index(op.f('ix_heartbeats_session_id'), 'heartbeats', ['session_id'], unique=False)
    op.create_index(op.f('ix_heartbeats_timestamp'), 'heartbeats', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_heartbeats_timestamp'), table_name='heartbeats')
    op.drop_index(op.f('ix_heartbeats_session_id'), table_name='heartbeats')
    op.drop_index(op.f('ix_heartbeats_id'), table_name='heartbeats')
    op.drop_table('heartbeats')
    op.drop_index(op.f('ix_work_sessions_user_id'), table_name='work_sessions')
    op.drop_index(op.f('ix_work_sessions_start_time'), table_name='work_sessions')
    op.drop_index(op.f('ix_work_sessions_id'), table_name='work_sessions')
    op.drop_index(op.f('ix_work_sessions_end_time'), table_name='work_sessions')
    op.drop_table('work_sessions')
    op.drop_index(op.f('ix_work_logs_user_id'), table_name='work_logs')
    op.drop_index(op.f('ix_work_logs_session_started_at'), table_name='work_logs')
    op.drop_index(op.f('ix_work_logs_session_ended_at'), table_name='work_logs')
    op.drop_index(op.f('ix_work_logs_id'), table_name='work_logs')
    op.drop_table('work_logs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_public_id'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_idle_episodes_user_id'), table_name='idle_episodes')
    op.drop_index(op.f('ix_idle_episodes_idle_started_at'), table_name='idle_episodes')
    op.drop_index(op.f('ix_idle_episodes_idle_ended_at'), table_name='idle_episodes')
    op.drop_index(op.f('ix_idle_episodes_id'), table_name='idle_episodes')
    op.drop_table('idle_episodes')
    # ### end Alembic commands ###
